package com.allash.bootdemo.model.mapper;

import com.allash.bootdemo.model.pojo.WUser;
import com.allash.bootdemo.model.pojo.WUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface WUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_user
     *
     * @mbg.generated Mon Jul 09 17:00:13 CST 2018
     */
    @SelectProvider(type=WUserSqlProvider.class, method="countByExample")
    long countByExample(WUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_user
     *
     * @mbg.generated Mon Jul 09 17:00:13 CST 2018
     */
    @DeleteProvider(type=WUserSqlProvider.class, method="deleteByExample")
    int deleteByExample(WUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_user
     *
     * @mbg.generated Mon Jul 09 17:00:13 CST 2018
     */
    @Delete({
        "delete from w_user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_user
     *
     * @mbg.generated Mon Jul 09 17:00:13 CST 2018
     */
    @Insert({
        "insert into w_user (username, password, ",
        "state)",
        "values (#{username,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR}, ",
        "#{state,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(WUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_user
     *
     * @mbg.generated Mon Jul 09 17:00:13 CST 2018
     */
    @InsertProvider(type=WUserSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(WUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_user
     *
     * @mbg.generated Mon Jul 09 17:00:13 CST 2018
     */
    @SelectProvider(type=WUserSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="username", property="username", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="state", property="state", jdbcType=JdbcType.INTEGER)
    })
    List<WUser> selectByExample(WUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_user
     *
     * @mbg.generated Mon Jul 09 17:00:13 CST 2018
     */
    @Select({
        "select",
        "id, username, password, state",
        "from w_user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="username", property="username", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="state", property="state", jdbcType=JdbcType.INTEGER)
    })
    WUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_user
     *
     * @mbg.generated Mon Jul 09 17:00:13 CST 2018
     */
    @UpdateProvider(type=WUserSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") WUser record, @Param("example") WUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_user
     *
     * @mbg.generated Mon Jul 09 17:00:13 CST 2018
     */
    @UpdateProvider(type=WUserSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") WUser record, @Param("example") WUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_user
     *
     * @mbg.generated Mon Jul 09 17:00:13 CST 2018
     */
    @UpdateProvider(type=WUserSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(WUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_user
     *
     * @mbg.generated Mon Jul 09 17:00:13 CST 2018
     */
    @Update({
        "update w_user",
        "set username = #{username,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "state = #{state,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(WUser record);
}