package com.allash.bootdemo.model.pojo;

public class WUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_user.id
     *
     * @mbg.generated Mon Jul 09 17:00:13 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_user.username
     *
     * @mbg.generated Mon Jul 09 17:00:13 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_user.password
     *
     * @mbg.generated Mon Jul 09 17:00:13 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_user.state
     *
     * @mbg.generated Mon Jul 09 17:00:13 CST 2018
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_user.id
     *
     * @return the value of w_user.id
     *
     * @mbg.generated Mon Jul 09 17:00:13 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_user.id
     *
     * @param id the value for w_user.id
     *
     * @mbg.generated Mon Jul 09 17:00:13 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_user.username
     *
     * @return the value of w_user.username
     *
     * @mbg.generated Mon Jul 09 17:00:13 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_user.username
     *
     * @param username the value for w_user.username
     *
     * @mbg.generated Mon Jul 09 17:00:13 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_user.password
     *
     * @return the value of w_user.password
     *
     * @mbg.generated Mon Jul 09 17:00:13 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_user.password
     *
     * @param password the value for w_user.password
     *
     * @mbg.generated Mon Jul 09 17:00:13 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_user.state
     *
     * @return the value of w_user.state
     *
     * @mbg.generated Mon Jul 09 17:00:13 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_user.state
     *
     * @param state the value for w_user.state
     *
     * @mbg.generated Mon Jul 09 17:00:13 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }
}